name: Print Selected Environment

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  print-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Extract pull request body
      id: extract-pr-body
      run: |
        # Read the pull request body
        PR_BODY=$(jq -r '.pull_request.body' < $GITHUB_EVENT_PATH)
        echo "$PR_BODY" > pr_body.txt

        # Debug: Display the pull request body
        echo "Debug: PR Body"
        cat pr_body.txt

        # Parse environment selections
        DEV_SELECTED=$(grep -i "Dev:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')
        STAGING_SELECTED=$(grep -i "Staging:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')
        PREPROD_SELECTED=$(grep -i "Preprod:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')
        PROD_SELECTED=$(grep -i "Prod:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')

        # Debug: Display parsed values
        echo "Debug: Parsed Environment Selections"
        echo "DEV_SELECTED=$DEV_SELECTED"
        echo "STAGING_SELECTED=$STAGING_SELECTED"
        echo "PREPROD_SELECTED=$PREPROD_SELECTED"
        echo "PROD_SELECTED=$PROD_SELECTED"

        # Export variables for subsequent steps
        echo "DEV_SELECTED=$DEV_SELECTED" >> $GITHUB_ENV
        echo "STAGING_SELECTED=$STAGING_SELECTED" >> $GITHUB_ENV
        echo "PREPROD_SELECTED=$PREPROD_SELECTED" >> $GITHUB_ENV
        echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV

    - name: Print selected environments
      run: |
        echo "Selected environments: "

        echo "Debug: Loaded environment variables"
        echo "DEV_SELECTED=$DEV_SELECTED"
        echo "STAGING_SELECTED=$STAGING_SELECTED"
        echo "PREPROD_SELECTED=$PREPROD_SELECTED"
        echo "PROD_SELECTED=$PROD_SELECcTED"

        if [ "$DEV_SELECTED" == "Y" ]; then
          echo "Dev: AP=$DEV_IMAGE_AP, EU=$DEV_IMAGE_EU, US=$DEV_IMAGE_US"
        fi
        if [ "$STAGING_SELECTED" == "Y" ]; then
          echo "Staging: AP=$STAGING_IMAGE_AP, EU=$STAGING_IMAGE_EU, US=$STAGING_IMAGE_US"
        fi
        if [ "$PREPROD_SELECTED" == "Y" ]; then
          echo "Preprod: AP=$PREPROD_IMAGE_AP, EU=$PREPROD_IMAGE_EU, US=$PREPROD_IMAGE_US"
        fi
        if [ "$PROD_SELECTED" == "Y" ]; then
          echo "Prod: AP=$PROD_IMAGE_AP, EU=$PROD_IMAGE_EU, US=$PROD_IMAGE_US"
        fi

      env:
        DEV_SELECTED: ${{ env.DEV_SELECTED }}
        STAGING_SELECTED: ${{ env.STAGING_SELECTED }}
        PREPROD_SELECTED: ${{ env.PREPROD_SELECTED }}
        PROD_SELECTED: ${{ env.PROD_SELECTED }}
        DEV_IMAGE_AP: ""
        DEV_IMAGE_EU: ""
        DEV_IMAGE_US: ""
        STAGING_IMAGE_AP: ""
        STAGING_IMAGE_EU: ""
        STAGING_IMAGE_US: ""
        PREPROD_IMAGE_AP: ""
        PREPROD_IMAGE_EU: ""
        PREPROD_IMAGE_US: ""
        PROD_IMAGE_AP: ""
        PROD_IMAGE_EU: ""
        PROD_IMAGE_US: ""
