name: Deployment Pipeline

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Pull Request Body
        id: extract
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < $GITHUB_EVENT_PATH)
          echo "Pull Request Body: $PR_BODY"

          # Extract environment selection
          DEV_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Dev: `)Y(?=`)' || echo "N")
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Staging: `)Y(?=`)' || echo "N")
          PREPROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Preprod: `)Y(?=`)' || echo "N")
          PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)Y(?=`)' || echo "N")

          echo "DEV_SELECTED=$DEV_SELECTED" >> $GITHUB_ENV
          echo "STAGING_SELECTED=$STAGING_SELECTED" >> $GITHUB_ENV
          echo "PREPROD_SELECTED=$PREPROD_SELECTED" >> $GITHUB_ENV
          echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV

          # Extract image tags
          if [[ "$DEV_SELECTED" == "Y" || "$STAGING_SELECTED" == "Y" ]]; then
            AP_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*AP Region:\*\* `).*?(?=`)' | head -1)
            EU_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*EU Region:\*\* `).*?(?=`)' | head -1)
            US_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*US Region:\*\* `).*?(?=`)' | head -1)
          elif [[ "$PREPROD_SELECTED" == "Y" || "$PROD_SELECTED" == "Y" ]]; then
            AP_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*AP Region:\*\* `).*?(?=`)' | head -1 || echo "")
            EU_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*EU Region:\*\* `).*?(?=`)' | head -1 || echo "")
            US_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=- \*\*US Region:\*\* `).*?(?=`)' | head -1 || echo "")
          fi

          echo "AP_IMAGE=$AP_IMAGE" >> $GITHUB_ENV
          echo "EU_IMAGE=$EU_IMAGE" >> $GITHUB_ENV
          echo "US_IMAGE=$US_IMAGE" >> $GITHUB_ENV

          echo "Selected Regions:"
          echo "AP_IMAGE=$AP_IMAGE"
          echo "EU_IMAGE=$EU_IMAGE"
          echo "US_IMAGE=$US_IMAGE"

      - name: Deploy to Selected Environment
        if: env.DEV_SELECTED == 'Y' || env.STAGING_SELECTED == 'Y' || env.PREPROD_SELECTED == 'Y' || env.PROD_SELECTED == 'Y'
        run: |
          if [[ "$DEV_SELECTED" == "Y" ]]; then
            echo "Deploying to Dev Environment with regions: AP=$AP_IMAGE, EU=$EU_IMAGE, US=$US_IMAGE"
          elif [[ "$STAGING_SELECTED" == "Y" ]]; then
            echo "Deploying to Staging Environment with regions: AP=$AP_IMAGE, EU=$EU_IMAGE, US=$US_IMAGE"
          elif [[ "$PREPROD_SELECTED" == "Y" ]]; then
            if [[ -n "$AP_IMAGE" || -n "$EU_IMAGE" || -n "$US_IMAGE" ]]; then
              echo "Deploying to Preprod Environment with regions: AP=$AP_IMAGE, EU=$EU_IMAGE, US=$US_IMAGE"
            else
              echo "Error: No region selected for Preprod."
              exit 1
            fi
          elif [[ "$PROD_SELECTED" == "Y" ]]; then
            if [[ -n "$AP_IMAGE" || -n "$EU_IMAGE" || -n "$US_IMAGE" ]]; then
              echo "Deploying to Prod Environment with regions: AP=$AP_IMAGE, EU=$EU_IMAGE, US=$US_IMAGE"
            else
              echo "Error: No region selected for Produ."
              exit 1
            fi
          fi
