name: Print Selected Environment

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  print-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Extract pull request body
      id: extract-pr-body
      run: |
        PR_BODY=$(jq -r '.pull_request.body' < $GITHUB_EVENT_PATH)
        echo "$PR_BODY" > pr_body.txt

        # Parse selection flags
        export DEV_SELECTED=$(grep -i "Dev:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export STAGING_SELECTED=$(grep -i "Staging:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export PREPROD_SELECTED=$(grep -i "Preprod:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export PROD_SELECTED=$(grep -i "Prod:" pr_body.txt | awk -F '`' '{print $2}' | tr -d '[:space:]')

        # Parse image values
        export DEV_IMAGE_AP=$(grep -A 3 "Dev Environment" pr_body.txt | grep "AP Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export DEV_IMAGE_EU=$(grep -A 3 "Dev Environment" pr_body.txt | grep "EU Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export DEV_IMAGE_US=$(grep -A 3 "Dev Environment" pr_body.txt | grep "US Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')

        export STAGING_IMAGE_AP=$(grep -A 3 "Staging Environment" pr_body.txt | grep "AP Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export STAGING_IMAGE_EU=$(grep -A 3 "Staging Environment" pr_body.txt | grep "EU Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export STAGING_IMAGE_US=$(grep -A 3 "Staging Environment" pr_body.txt | grep "US Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')

        export PREPROD_IMAGE_AP=$(grep -A 3 "Preprod Environment" pr_body.txt | grep "AP Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export PREPROD_IMAGE_EU=$(grep -A 3 "Preprod Environment" pr_body.txt | grep "EU Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export PREPROD_IMAGE_US=$(grep -A 3 "Preprod Environment" pr_body.txt | grep "US Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')

        export PROD_IMAGE_AP=$(grep -A 3 "Prod Environment" pr_body.txt | grep "AP Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export PROD_IMAGE_EU=$(grep -A 3 "Prod Environment" pr_body.txt | grep "EU Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')
        export PROD_IMAGE_US=$(grep -A 3 "Prod Environment" pr_body.txt | grep "US Region:" | awk -F '`' '{print $2}' | tr -d '[:space:]')

        # Export variables for the next steps
        echo "DEV_SELECTED=$DEV_SELECTED" >> $GITHUB_ENV
        echo "STAGING_SELECTED=$STAGING_SELECTED" >> $GITHUB_ENV
        echo "PREPROD_SELECTED=$PREPROD_SELECTED" >> $GITHUB_ENV
        echo "PROD_SELECTED=$PROD_SELECTED" >> $GITHUB_ENV

        echo "DEV_IMAGE_AP=$DEV_IMAGE_AP" >> $GITHUB_ENV
        echo "DEV_IMAGE_EU=$DEV_IMAGE_EU" >> $GITHUB_ENV
        echo "DEV_IMAGE_US=$DEV_IMAGE_US" >> $GITHUB_ENV

        echo "STAGING_IMAGE_AP=$STAGING_IMAGE_AP" >> $GITHUB_ENV
        echo "STAGING_IMAGE_EU=$STAGING_IMAGE_EU" >> $GITHUB_ENV
        echo "STAGING_IMAGE_US=$STAGING_IMAGE_US" >> $GITHUB_ENV

        echo "PREPROD_IMAGE_AP=$PREPROD_IMAGE_AP" >> $GITHUB_ENV
        echo "PREPROD_IMAGE_EU=$PREPROD_IMAGE_EU" >> $GITHUB_ENV
        echo "PREPROD_IMAGE_US=$PREPROD_IMAGE_US" >> $GITHUB_ENV

        echo "PROD_IMAGE_AP=$PROD_IMAGE_AP" >> $GITHUB_ENV
        echo "PROD_IMAGE_EU=$PROD_IMAGE_EU" >> $GITHUB_ENV
        echo "PROD_IMAGE_US=$PROD_IMAGE_US" >> $GITHUB_ENV

    - name: Debug selected environment values
      run: |
        echo "DEV_SELECTED=$DEV_SELECTED"
        echo "STAGING_SELECTED=$STAGING_SELECTED"
        echo "PREPROD_SELECTED=$PREPROD_SELECTED"
        echo "PROD_SELECTED=$PROD_SELECTED"

    - name: Print selected environment values
      run: |
        echo "Selected environments: "
        
        if [ "$DEV_SELECTED" == "Y" ]; then
          echo "Dev: AP=$DEV_IMAGE_AP, EU=$DEV_IMAGE_EU, US=$DEV_IMAGE_US"
        fi
        if [ "$STAGING_SELECTED" == "Y" ]; then
          echo "Staging: AP=$STAGING_IMAGE_AP, EU=$STAGING_IMAGE_EU, US=$STAGING_IMAGE_US"
        fi
        if [ "$PREPROD_SELECTED" == "Y" ]; then
          echo "Preprod: AP=$PREPROD_IMAGE_AP, EU=$PREPROD_IMAGE_EU, US=$PREPROD_IMAGE_US"
        fi
        if [ "$PROD_SELECTED" == "Y" ]; then
          echo "Prod: AP=$PROD_IMAGE_AP, EU=$PROD_IMAGE_EU, US=$PROD_IMAGE_US"
        fi
