name: Deployment Pipeline

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Pull Request Body
        id: extract
        run: |
          PR_BODY=$(jq -r '.pull_request.body' < $GITHUB_EVENT_PATH)
          echo "Pull Request Body: $PR_BODY"

          # Extract environment selections (Dev, Staging, Preprod, Prod)
          DEV_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Dev: `)Y(?=`)' || echo "N")
          STAGING_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Staging: `)Y(?=`)' || echo "N")
          PREPROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Preprod: `)Y(?=`)' || echo "N")
          PROD_SELECTED=$(echo "$PR_BODY" | grep -oP '(?<=- Prod: `)Y(?=`)' || echo "N")

          # Debugging: Show the environment selections
          echo "DEV_SELECTED: $DEV_SELECTED"
          echo "STAGING_SELECTED: $STAGING_SELECTED"
          echo "PREPROD_SELECTED: $PREPROD_SELECTED"
          echo "PROD_SELECTED: $PROD_SELECTED"

          # Extract image tags based on environment selection
          if [[ "$DEV_SELECTED" == "Y" ]]; then
            SELECTED_ENV="Dev"
            AP_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Dev Environment).*?AP Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            EU_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Dev Environment).*?EU Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            US_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Dev Environment).*?US Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
          elif [[ "$STAGING_SELECTED" == "Y" ]]; then
            SELECTED_ENV="Staging"
            AP_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Staging Environment).*?AP Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            EU_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Staging Environment).*?EU Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            US_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Staging Environment).*?US Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
          elif [[ "$PREPROD_SELECTED" == "Y" ]]; then
            SELECTED_ENV="Preprod"
            AP_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Preprod Environment).*?AP Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            EU_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Preprod Environment).*?EU Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            US_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Preprod Environment).*?US Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
          elif [[ "$PROD_SELECTED" == "Y" ]]; then
            SELECTED_ENV="Prod"
            AP_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Prod Environment).*?AP Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            EU_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Prod Environment).*?EU Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
            US_IMAGE=$(echo "$PR_BODY" | grep -oP '(?<=Prod Environment).*?US Region:\*\* `.*?`' | grep -oP '(?<=`).*?(?=`)')
          fi

          # Debugging: Show selected environment and image tags
          echo "SELECTED_ENV: $SELECTED_ENV"
          echo "AP_IMAGE: $AP_IMAGE"
          echo "EU_IMAGE: $EU_IMAGE"
          echo "US_IMAGE: $US_IMAGE"

          echo "SELECTED_ENV=$SELECTED_ENV" >> $GITHUB_ENV
          echo "AP_IMAGE=$AP_IMAGE" >> $GITHUB_ENV
          echo "EU_IMAGE=$EU_IMAGE" >> $GITHUB_ENV
          echo "US_IMAGE=$US_IMAGE" >> $GITHUB_ENV

      - name: Deploy to Selected Environment
        if: env.SELECTED_ENV
        run: |
          echo "Deploying to $SELECTED_ENV Environment with regions:"
          
          # Only print the regions for the selected environment
          if [[ "$SELECTED_ENV" == "Dev" ]]; then
            [[ -n "$AP_IMAGE" ]] && echo "AP=$AP_IMAGE"
            [[ -n "$EU_IMAGE" ]] && echo "EU=$EU_IMAGE"
            [[ -n "$US_IMAGE" ]] && echo "US=$US_IMAGE"
          elif [[ "$SELECTED_ENV" == "Staging" ]]; then
            [[ -n "$AP_IMAGE" ]] && echo "AP=$AP_IMAGE"
            [[ -n "$EU_IMAGE" ]] && echo "EU=$EU_IMAGE"
            [[ -n "$US_IMAGE" ]] && echo "US=$US_IMAGE"
          elif [[ "$SELECTED_ENV" == "Preprod" ]]; then
            [[ -n "$AP_IMAGE" ]] && echo "AP=$AP_IMAGE"
            [[ -n "$EU_IMAGE" ]] && echo "EU=$EU_IMAGE"
            [[ -n "$US_IMAGE" ]] && echo "US=$US_IMAGE"
          elif [[ "$SELECTED_ENV" == "Prod" ]]; then
            [[ -n "$AP_IMAGE" ]] && echo "AP=$AP_IMAGE"
            [[ -n "$EU_IMAGE" ]] && echo "EU=$EU_IMAGE"
            [[ -n "$US_IMAGE" ]] && echo "US=$US_IMAGE"
